NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

TrajectoryPlannerROS:
  max_vel_x: 10.0
  min_vel_x: 1.0
  max_vel_theta: 1.0
  min_in_place_vel_theta: 1.0

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true
  
  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1
  
DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2

  max_vel_x: 10.0
  min_vel_x: 1.0
  max_vel_y: 10.0
  min_vel_y: 1.0

  max_trans_vel: 10.0
  min_trans_vel: 1.0
  max_rot_vel: 5.0
  min_rot_vel: 1.0

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false
